spring:
  cloud:
    gateway:
      routes:
        - id: test_route
          uri: https://www.baidu.com
          predicates:
            - Query=url, baidu # 访问地址为：http://localhost:88/test_route?url=baidu,baidu为正则表达式
        - id: qq_route
          uri: https://www.qq.com
          predicates:
            - Query=url, qq # 访问地址为：http://localhost:88/qq_route?url=qq,qq为正则表达式